model_params:
    name: VGG
    num_classes: 10
    freeze_layers: False
    bce: False

data_params:
    name: Galaxy10
    image_size: 128
    train_root: ../Galaxy10/galaxy10_data/image_data_train/
    test_root: ../Galaxy10/galaxy10_data/image_data_test/
    train_batch_size: 256
    val_batch_size:   128
    test_batch_size:  128
    num_workers: 8
    pin_memory: True
    download: False
    
exp_params:
    name: Classifier
    task: multiclass
    LR:   0.0001
    weight_decay: 0.0005
    scheduler_gamma: 0.875

trainer_params:
    accelerator: 'gpu'
    # devices: [5]
    max_epochs: 50
    log_every_n_steps: 10
    check_val_every_n_epoch: 1
    gradient_clip_val: 10.
    #strategy: 'ddp_find_unused_parameters_true'

logging_params:
    save_dir: "logs/"
    name: "Galaxy10_VGG"